// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUKJHqzxH-9e9zcMdDaLCxdf3G_wfCivY',
    appId: '1:492221240705:web:7c6036e4633f9375acc480',
    messagingSenderId: '492221240705',
    projectId: 'events-agency-18c18',
    authDomain: 'events-agency-18c18.firebaseapp.com',
    storageBucket: 'events-agency-18c18.firebasestorage.app',
    measurementId: 'G-4RX4Q3M179',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CTizSH_h6W0TN9YGea3eUa1rN0GyALs',
    appId: '1:492221240705:android:4eb83114f5f7faa3acc480',
    messagingSenderId: '492221240705',
    projectId: 'events-agency-18c18',
    storageBucket: 'events-agency-18c18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcg1RaJTD9TbutklxJwJx7vUwOrUfgUMo',
    appId: '1:492221240705:ios:3b87ebb4a8a3b753acc480',
    messagingSenderId: '492221240705',
    projectId: 'events-agency-18c18',
    storageBucket: 'events-agency-18c18.firebasestorage.app',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcg1RaJTD9TbutklxJwJx7vUwOrUfgUMo',
    appId: '1:492221240705:ios:3b87ebb4a8a3b753acc480',
    messagingSenderId: '492221240705',
    projectId: 'events-agency-18c18',
    storageBucket: 'events-agency-18c18.firebasestorage.app',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUKJHqzxH-9e9zcMdDaLCxdf3G_wfCivY',
    appId: '1:492221240705:web:441240ba9e6453c8acc480',
    messagingSenderId: '492221240705',
    projectId: 'events-agency-18c18',
    authDomain: 'events-agency-18c18.firebaseapp.com',
    storageBucket: 'events-agency-18c18.firebasestorage.app',
    measurementId: 'G-F066MCHQS8',
  );
}
